// 各种请求状态常量

// 获取广告数据
export const GET_ADLIST = 'GET_ADLIST'
export const GET_ADLIST_REQUEST = 'GET_ADLIST_REQUEST'
export const GET_ADLIST_SUCCESS = 'GET_ADLIST_SUCCESS'
export const GET_ADLIST_FAILURE = 'GET_ADLIST_FAILURE'


// 获取用户信息
export const GET_USERINFO = 'GET_USERINFO'
export const GET_USERINFO_REQUEST = 'GET_USERINFO_REQUEST'
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAILURE = 'GET_USERINFO_FAILURE'

// 获取首页卡片信息
export const GET_HOMECARD = 'GET_HOMECARD'
export const GET_HOMECARD_REQUEST = 'GET_HOMECARD_REQUEST'
export const GET_HOMECARD_SUCCESS = 'GET_HOMECARD_SUCCESS'
export const GET_HOMECARD_FAILURE = 'GET_HOMECARD_FAILURE'

// 全局数据
export const ADRESS_UPDATE = 'ADRESS_UPDATE'